### ISSUE TITLE
High dimension feature embedding visualization

### ISSUE THREAD

**Issue by hfutzzw** [KaiyangZhou/pytorch-center-loss#15]
Hi, Kaiyang. The feature embedding is 2-dim in this repository and it is straightforward to visualize.
But if the feature is in a high-dimension space (e.g 2048, ResNet50 GAP feature). How I visualize 
it in 2-d feature space, should I utilize the approaches such as PCA or TSNE ?

**Comment by caijie0620** [comment]
Yes, you can use tsne to visualize high-dimension data.
